package View;

import controller.Listener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

public class DashboardPembeli extends javax.swing.JFrame {

    Listener listener;
    
    public DashboardPembeli() {
        initComponents();
    }

    public JLabel getLabelHarga() {
        return LabelHarga;
    }

    public JLabel getLabelJumlahKamar() {
        return LabelJumlahKamar;
    }

    public JLabel getLabelNama() {
        return LabelNama;
    }

    public void setListener(Listener listener) {
        this.listener = listener;
    }

    public JLabel getAlamatRumah() {
        return AlamatRumah;
    }

    public JLabel getDashboardPembeli() {
        return DashboardPembeli;
    }

    public JToggleButton getFormPengajuan() {
        return FormPengajuan;
    }

    public JLabel getHarga() {
        return Harga;
    }

    public JLabel getJumlahKamar() {
        return JumlahKamar;
    }

    public JLabel getJumlahLantai() {
        return JumlahLantai;
    }

    public JLabel getJumlahParkir() {
        return JumlahParkir;
    }

    public JLabel getJumlahToilet() {
        return JumlahToilet;
    }

    public JLabel getKeterangan1() {
        return Keterangan1;
    }

    public JLabel getKeterangan2() {
        return Keterangan2;
    }

    public JToggleButton getLihatDaftarRumah() {
        return LihatDaftarRumah;
    }

    public JButton getLogout() {
        return Logout;
    }

    public JLabel getLuasBangunan() {
        return LuasBangunan;
    }

    public JLabel getLuasTanah() {
        return LuasTanah;
    }

    public JLabel getNamaRumahField() {
        return NamaRumahField;
    }

    public JToggleButton getSearch() {
        return Search;
    }

    public JButton getSubmitForm() {
        return SubmitForm;
    }

    public JButton getSubmitSearch1() {
        return SubmitSearch1;
    }

    public JLabel getTabelAlamat() {
        return TabelAlamat;
    }

    public JTable getTableDatarRumah() {
        return TableDatarRumah;
    }

    public JLabel getTanggalJanjianField() {
        return TanggalJanjianField;
    }

    public JTextField getTextFieldHarga() {
        return TextFieldHarga;
    }

    public JTextField getTextFieldJumlahKamar() {
        return TextFieldJumlahKamar;
    }

    public JTextField getTextFieldNama() {
        return TextFieldNama;
    }

    public JTextField getTextFieldNamaRumah() {
        return TextFieldNamaRumah;
    }

    public JLabel getWaktuJanjianField() {
        return WaktuJanjianField;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JComboBox<String> getjComboBox2() {
        return jComboBox2;
    }

    public JComboBox<String> getjComboBox3() {
        return jComboBox3;
    }

    public JComboBox<String> getjComboBox4() {
        return jComboBox4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JToggleButton getLihatFormPengajuan() {
        return LihatFormPengajuan;
    }

    public JTable getTableForm() {
        return jTable1;
    }

    public JScrollPane getTablePengajuanForm() {
        return TablePengajuanForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DashboardPembeli = new javax.swing.JLabel();
        Search = new javax.swing.JToggleButton();
        LihatDaftarRumah = new javax.swing.JToggleButton();
        FormPengajuan = new javax.swing.JToggleButton();
        LihatFormPengajuan = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldHarga = new javax.swing.JTextField();
        TextFieldJumlahKamar = new javax.swing.JTextField();
        Keterangan1 = new javax.swing.JLabel();
        Keterangan2 = new javax.swing.JLabel();
        SubmitForm = new javax.swing.JButton();
        TabelAlamat = new javax.swing.JLabel();
        AlamatRumah = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        JumlahKamar = new javax.swing.JLabel();
        LuasBangunan = new javax.swing.JLabel();
        LuasTanah = new javax.swing.JLabel();
        JumlahParkir = new javax.swing.JLabel();
        JumlahLantai = new javax.swing.JLabel();
        JumlahToilet = new javax.swing.JLabel();
        TextFieldNamaRumah = new javax.swing.JTextField();
        NamaRumahField = new javax.swing.JLabel();
        WaktuJanjianField = new javax.swing.JLabel();
        TanggalJanjianField = new javax.swing.JLabel();
        SubmitSearch1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDatarRumah = new javax.swing.JTable();
        LabelNama = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        LabelJumlahKamar = new javax.swing.JLabel();
        TablePengajuanForm = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardPembeli.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        DashboardPembeli.setForeground(new java.awt.Color(204, 102, 0));
        DashboardPembeli.setText("Dashboard Pembeli");
        jPanel1.add(DashboardPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, 217, -1));

        Search.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(Search);
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, -1));

        LihatDaftarRumah.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(LihatDaftarRumah);
        LihatDaftarRumah.setForeground(new java.awt.Color(255, 255, 255));
        LihatDaftarRumah.setText("LihatDaftarRumah");
        LihatDaftarRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatDaftarRumahActionPerformed(evt);
            }
        });
        jPanel1.add(LihatDaftarRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, -1));

        FormPengajuan.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(FormPengajuan);
        FormPengajuan.setForeground(new java.awt.Color(255, 255, 255));
        FormPengajuan.setText("Form Pengajuan");
        FormPengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormPengajuanActionPerformed(evt);
            }
        });
        jPanel1.add(FormPengajuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, -1));

        LihatFormPengajuan.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(LihatFormPengajuan);
        LihatFormPengajuan.setForeground(new java.awt.Color(255, 255, 255));
        LihatFormPengajuan.setText("Liihat Form Pengajuan");
        LihatFormPengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatFormPengajuanActionPerformed(evt);
            }
        });
        jPanel1.add(LihatFormPengajuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(TextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 390, -1));
        jPanel2.add(TextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 90, -1));
        jPanel2.add(TextFieldJumlahKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 90, -1));

        Keterangan1.setText("<");
        jPanel2.add(Keterangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, -1, -1));

        Keterangan2.setText("<");
        jPanel2.add(Keterangan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, -1, -1));

        SubmitForm.setBackground(new java.awt.Color(204, 102, 0));
        SubmitForm.setForeground(new java.awt.Color(255, 255, 255));
        SubmitForm.setText("Submit");
        SubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitFormActionPerformed(evt);
            }
        });
        jPanel2.add(SubmitForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        TabelAlamat.setText("Alamat :");
        jPanel2.add(TabelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        AlamatRumah.setText("Nama Rumah :");
        jPanel2.add(AlamatRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 20));

        Harga.setText("Harga :");
        jPanel2.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        JumlahKamar.setText("Jumlah Kamar :");
        jPanel2.add(JumlahKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 20));

        LuasBangunan.setText("Luas Bangunan :");
        jPanel2.add(LuasBangunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 20));

        LuasTanah.setText("Luas Tanah");
        jPanel2.add(LuasTanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, 20));

        JumlahParkir.setText("Jumlah Parkir :");
        jPanel2.add(JumlahParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 20));

        JumlahLantai.setText("Jumlah Lantai :");
        jPanel2.add(JumlahLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, 20));

        JumlahToilet.setText("Jumlah Toilet : ");
        jPanel2.add(JumlahToilet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, 20));

        TextFieldNamaRumah.setEditable(false);
        jPanel2.add(TextFieldNamaRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, -1));

        NamaRumahField.setText("Nama Rumah :");
        jPanel2.add(NamaRumahField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        WaktuJanjianField.setText("Waktu Janjian :");
        jPanel2.add(WaktuJanjianField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        TanggalJanjianField.setText("Tanggal Janjian :");
        jPanel2.add(TanggalJanjianField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        SubmitSearch1.setBackground(new java.awt.Color(204, 102, 0));
        SubmitSearch1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitSearch1.setText("Submit");
        SubmitSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSearch1ActionPerformed(evt);
            }
        });
        jPanel2.add(SubmitSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, -1, -1));

        Logout.setBackground(new java.awt.Color(204, 102, 0));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", " " }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        TableDatarRumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Rumah", "Alamat Rumah", "Harga"
            }
        ));
        TableDatarRumah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDatarRumahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDatarRumah);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 740, 260));

        LabelNama.setText("Nama :");
        jPanel2.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        LabelHarga.setText("Harga :");
        jPanel2.add(LabelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, -1));

        LabelJumlahKamar.setText("Jumlah Kamar :");
        jPanel2.add(LabelJumlahKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePengajuanForm.setViewportView(jTable1);

        jPanel2.add(TablePengajuanForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 740, 260));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1040, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitFormActionPerformed
        listener.submitForm();
    }//GEN-LAST:event_SubmitFormActionPerformed

    private void SubmitSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSearch1ActionPerformed
        listener.Search();
    }//GEN-LAST:event_SubmitSearch1ActionPerformed

    private void LihatDaftarRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatDaftarRumahActionPerformed
        listener.pilihanPembeli();
        listener.isiTabel();
    }//GEN-LAST:event_LihatDaftarRumahActionPerformed

    private void FormPengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormPengajuanActionPerformed
        listener.pilihanPembeli();
    }//GEN-LAST:event_FormPengajuanActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        listener.pilihanPembeli();
    }//GEN-LAST:event_SearchActionPerformed

    private void TableDatarRumahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDatarRumahMouseClicked
        listener.isiField(TableDatarRumah.getSelectedRow());
        listener.isiComboBox(TableDatarRumah.getSelectedRow());
    }//GEN-LAST:event_TableDatarRumahMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        listener.LogOut();
    }//GEN-LAST:event_LogoutActionPerformed

    private void LihatFormPengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatFormPengajuanActionPerformed
        listener.pilihanPembeli();
        listener.isiTabel();
    }//GEN-LAST:event_LihatFormPengajuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatRumah;
    private javax.swing.JLabel DashboardPembeli;
    private javax.swing.JToggleButton FormPengajuan;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel JumlahKamar;
    private javax.swing.JLabel JumlahLantai;
    private javax.swing.JLabel JumlahParkir;
    private javax.swing.JLabel JumlahToilet;
    private javax.swing.JLabel Keterangan1;
    private javax.swing.JLabel Keterangan2;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelJumlahKamar;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JToggleButton LihatDaftarRumah;
    private javax.swing.JToggleButton LihatFormPengajuan;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel LuasBangunan;
    private javax.swing.JLabel LuasTanah;
    private javax.swing.JLabel NamaRumahField;
    private javax.swing.JToggleButton Search;
    private javax.swing.JButton SubmitForm;
    private javax.swing.JButton SubmitSearch1;
    private javax.swing.JLabel TabelAlamat;
    private javax.swing.JTable TableDatarRumah;
    private javax.swing.JScrollPane TablePengajuanForm;
    private javax.swing.JLabel TanggalJanjianField;
    private javax.swing.JTextField TextFieldHarga;
    private javax.swing.JTextField TextFieldJumlahKamar;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNamaRumah;
    private javax.swing.JLabel WaktuJanjianField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
