package View;

import controller.Listener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

public class DashboardAgency extends javax.swing.JFrame {

    Listener listener;
    
    public DashboardAgency() {
        initComponents();
    }

    public void setListener(Listener listener) {
        this.listener = listener;
    }

    public JTextField getAlamatField() {
        return AlamatField;
    }

    public JLabel getAlamatLabel() {
        return AlamatLabel;
    }

    public JLabel getAlamatLabelField() {
        return AlamatLabelField;
    }

    public JButton getButtonLogout() {
        return ButtonLogout;
    }

    public JButton getButtonSubmit() {
        return ButtonSubmit;
    }

    public JLabel getDataRumahBaruLabelField() {
        return DataRumahBaruLabelField;
    }

    public JTextField getHargaField() {
        return HargaField;
    }

    public JLabel getHargaLabel() {
        return HargaLabel;
    }

    public JLabel getHargaLabelField() {
        return HargaLabelField;
    }

    public JLabel getIDLabel() {
        return IDLabel;
    }

    public JTextField getJumlahKamarField() {
        return JumlahKamarField;
    }

    public JLabel getJumlahKamarLabel() {
        return JumlahKamarLabel;
    }

    public JLabel getJumlahKamarLabelField() {
        return JumlahKamarLabelField;
    }

    public JLabel getJumlahLantaiLabel() {
        return JumlahLantaiLabel;
    }

    public JLabel getJumlahLantaiLabelField() {
        return JumlahLantaiLabelField;
    }

    public JTextField getJumlahParkirField() {
        return JumlahParkirField;
    }

    public JLabel getJumlahParkirLabel() {
        return JumlahParkirLabel;
    }

    public JLabel getJumlahParkirLabelField() {
        return JumlahParkirLabelField;
    }

    public JTextField getJumlahToiletField() {
        return JumlahToiletField;
    }

    public JLabel getJumlahToiletLabel() {
        return JumlahToiletLabel;
    }

    public JLabel getJumlahToiletLabelField() {
        return JumlahToiletLabelField;
    }

    public JTextField getJumlajLantaiField() {
        return JumlajLantaiField;
    }

    public JLabel getKodeAgencyLabel() {
        return KodeAgencyLabel;
    }

    public JToggleButton getLihatDaftarRumah() {
        return LihatDaftarRumah;
    }

    public JTextField getLuasBangunanField() {
        return LuasBangunanField;
    }

    public JLabel getLuasBangunanLabel() {
        return LuasBangunanLabel;
    }

    public JLabel getLuasBangunanLabelField() {
        return LuasBangunanLabelField;
    }

    public JTextField getLuasTanahField() {
        return LuasTanahField;
    }

    public JLabel getLuasTanahLabel() {
        return LuasTanahLabel;
    }

    public JLabel getLuasTanahLabelField() {
        return LuasTanahLabelField;
    }

    public JTextField getNamaRumahField() {
        return NamaRumahField;
    }

    public JLabel getNamaRumahLabel() {
        return NamaRumahLabel;
    }

    public JLabel getNamaRumahLabelField() {
        return NamaRumahLabelField;
    }

    public JTable getTableDataRumah() {
        return TableDataRumah;
    }

    public JToggleButton getTambahDataRumah() {
        return TambahDataRumah;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getTabelPengajuanDataRumah() {
        return TabelPengajuanDataRumah;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LihatDaftarRumah = new javax.swing.JToggleButton();
        TambahDataRumah = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        DataRumahBaruLabelField = new javax.swing.JLabel();
        AlamatLabelField = new javax.swing.JLabel();
        NamaRumahLabelField = new javax.swing.JLabel();
        HargaLabelField = new javax.swing.JLabel();
        JumlahKamarLabelField = new javax.swing.JLabel();
        LuasBangunanLabelField = new javax.swing.JLabel();
        LuasTanahLabelField = new javax.swing.JLabel();
        JumlahParkirLabelField = new javax.swing.JLabel();
        JumlahLantaiLabelField = new javax.swing.JLabel();
        JumlahToiletLabelField = new javax.swing.JLabel();
        JumlahToiletField = new javax.swing.JTextField();
        AlamatField = new javax.swing.JTextField();
        NamaRumahField = new javax.swing.JTextField();
        HargaField = new javax.swing.JTextField();
        JumlahKamarField = new javax.swing.JTextField();
        LuasBangunanField = new javax.swing.JTextField();
        LuasTanahField = new javax.swing.JTextField();
        JumlahParkirField = new javax.swing.JTextField();
        JumlajLantaiField = new javax.swing.JTextField();
        ButtonSubmit = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        KodeAgencyLabel = new javax.swing.JLabel();
        AlamatLabel = new javax.swing.JLabel();
        NamaRumahLabel = new javax.swing.JLabel();
        HargaLabel = new javax.swing.JLabel();
        JumlahKamarLabel = new javax.swing.JLabel();
        LuasBangunanLabel = new javax.swing.JLabel();
        LuasTanahLabel = new javax.swing.JLabel();
        JumlahParkirLabel = new javax.swing.JLabel();
        JumlahLantaiLabel = new javax.swing.JLabel();
        JumlahToiletLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDataRumah = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPengajuanDataRumah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Dashboard Agency");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, 217, -1));

        LihatDaftarRumah.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(LihatDaftarRumah);
        LihatDaftarRumah.setForeground(new java.awt.Color(255, 255, 255));
        LihatDaftarRumah.setText("LihatDaftarRumah");
        LihatDaftarRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatDaftarRumahActionPerformed(evt);
            }
        });
        jPanel1.add(LihatDaftarRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 136, 160, -1));

        TambahDataRumah.setBackground(new java.awt.Color(204, 102, 0));
        buttonGroup1.add(TambahDataRumah);
        TambahDataRumah.setForeground(new java.awt.Color(255, 255, 255));
        TambahDataRumah.setText("TambahDataRumah");
        TambahDataRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahDataRumahActionPerformed(evt);
            }
        });
        jPanel1.add(TambahDataRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 80, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DataRumahBaruLabelField.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        DataRumahBaruLabelField.setForeground(new java.awt.Color(204, 102, 0));
        DataRumahBaruLabelField.setText("Data Rumah Baru :");
        jPanel2.add(DataRumahBaruLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        AlamatLabelField.setText("Alamat :");
        jPanel2.add(AlamatLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        NamaRumahLabelField.setText("Nama Rumah :");
        jPanel2.add(NamaRumahLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        HargaLabelField.setText("Harga :");
        jPanel2.add(HargaLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        JumlahKamarLabelField.setText("Jumlah Kamar :");
        jPanel2.add(JumlahKamarLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        LuasBangunanLabelField.setText("Luas Bangunan :");
        jPanel2.add(LuasBangunanLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        LuasTanahLabelField.setText("Luas Tanah :");
        jPanel2.add(LuasTanahLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        JumlahParkirLabelField.setText("Jumlah Parkir :");
        jPanel2.add(JumlahParkirLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        JumlahLantaiLabelField.setText("Jumlah Lantai :");
        jPanel2.add(JumlahLantaiLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        JumlahToiletLabelField.setText("Jumlah Toilet :");
        jPanel2.add(JumlahToiletLabelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));
        jPanel2.add(JumlahToiletField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 200, -1));
        jPanel2.add(AlamatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 200, -1));
        jPanel2.add(NamaRumahField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 200, -1));
        jPanel2.add(HargaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 200, -1));
        jPanel2.add(JumlahKamarField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, -1));

        LuasBangunanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasBangunanFieldActionPerformed(evt);
            }
        });
        jPanel2.add(LuasBangunanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 200, -1));

        LuasTanahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasTanahFieldActionPerformed(evt);
            }
        });
        jPanel2.add(LuasTanahField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 200, -1));
        jPanel2.add(JumlahParkirField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 200, -1));
        jPanel2.add(JumlajLantaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 200, -1));

        ButtonSubmit.setBackground(new java.awt.Color(204, 102, 0));
        ButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        ButtonLogout.setBackground(new java.awt.Color(204, 102, 0));
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        IDLabel.setText("ID :");
        jPanel2.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        KodeAgencyLabel.setText("Kode Agensi :");
        jPanel2.add(KodeAgencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        AlamatLabel.setText("Alamat :");
        jPanel2.add(AlamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        NamaRumahLabel.setText("Nama Rumah :");
        jPanel2.add(NamaRumahLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        HargaLabel.setText("Harga :");
        jPanel2.add(HargaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        JumlahKamarLabel.setText("Jumlah Kamar : ");
        jPanel2.add(JumlahKamarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        LuasBangunanLabel.setText("Luas Bangunan :");
        jPanel2.add(LuasBangunanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        LuasTanahLabel.setText("Luas Tanah :");
        jPanel2.add(LuasTanahLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        JumlahParkirLabel.setText("Jumlah Parkir : ");
        jPanel2.add(JumlahParkirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        JumlahLantaiLabel.setText("Jumlah Lantai : ");
        jPanel2.add(JumlahLantaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        JumlahToiletLabel.setText("Jumlah Toilet :");
        jPanel2.add(JumlahToiletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TableDataRumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Rumah", "Alamat Rumah", "Harga"
            }
        ));
        TableDataRumah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataRumahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDataRumah);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 190));

        TabelPengajuanDataRumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Alamat", "Harga (Juta(", "Luas Bangunan"
            }
        ));
        jScrollPane2.setViewportView(TabelPengajuanDataRumah);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1040, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TambahDataRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahDataRumahActionPerformed
        listener.isiTabel();
        listener.pilihanAgensi();
    }//GEN-LAST:event_TambahDataRumahActionPerformed

    private void LihatDaftarRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatDaftarRumahActionPerformed
        listener.isiTabel();
        listener.pilihanAgensi();
    }//GEN-LAST:event_LihatDaftarRumahActionPerformed

    private void TableDataRumahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataRumahMouseClicked
        listener.isiField(TableDataRumah.getSelectedRow());
    }//GEN-LAST:event_TableDataRumahMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        listener.isiField(TableDataRumah.getSelectedRow());
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        listener.LogOut();
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        listener.submitRumah();
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    private void LuasTanahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasTanahFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuasTanahFieldActionPerformed

    private void LuasBangunanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasBangunanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuasBangunanFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAgency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatField;
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JLabel AlamatLabelField;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JLabel DataRumahBaruLabelField;
    private javax.swing.JTextField HargaField;
    private javax.swing.JLabel HargaLabel;
    private javax.swing.JLabel HargaLabelField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField JumlahKamarField;
    private javax.swing.JLabel JumlahKamarLabel;
    private javax.swing.JLabel JumlahKamarLabelField;
    private javax.swing.JLabel JumlahLantaiLabel;
    private javax.swing.JLabel JumlahLantaiLabelField;
    private javax.swing.JTextField JumlahParkirField;
    private javax.swing.JLabel JumlahParkirLabel;
    private javax.swing.JLabel JumlahParkirLabelField;
    private javax.swing.JTextField JumlahToiletField;
    private javax.swing.JLabel JumlahToiletLabel;
    private javax.swing.JLabel JumlahToiletLabelField;
    private javax.swing.JTextField JumlajLantaiField;
    private javax.swing.JLabel KodeAgencyLabel;
    private javax.swing.JToggleButton LihatDaftarRumah;
    private javax.swing.JTextField LuasBangunanField;
    private javax.swing.JLabel LuasBangunanLabel;
    private javax.swing.JLabel LuasBangunanLabelField;
    private javax.swing.JTextField LuasTanahField;
    private javax.swing.JLabel LuasTanahLabel;
    private javax.swing.JLabel LuasTanahLabelField;
    private javax.swing.JTextField NamaRumahField;
    private javax.swing.JLabel NamaRumahLabel;
    private javax.swing.JLabel NamaRumahLabelField;
    private javax.swing.JTable TabelPengajuanDataRumah;
    private javax.swing.JTable TableDataRumah;
    private javax.swing.JToggleButton TambahDataRumah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
